# Generated by Django 3.2.8 on 2021-10-28 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20211028_2129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='vot_ratio',
            new_name='vote_ratio',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='vot_total',
            new_name='vote_total',
        ),
    ]
