# Generated by Django 3.2.8 on 2021-10-31 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_project_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='projects/'),
        ),
    ]
